### ISSUE TITLE
Hi How to change outer color programmatically in slide to Act view

### ISSUE THREAD

**Issue by jesuvijay** [cortinico/slidetoact#10]
## What kind of issue is this?

 - [ ] UI Bug. Please provide a Screenshot/Video/GIF of what's the problem. If you need help to record a video you can follow [this guide](https://developer.android.com/studio/command-line/adb.html#screenrecord)

 - [ ] Functional Bug. Please describe the scenario of the bug. Furthermore, please spend the time to write a failing test.

 - [x] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

In case of bug report, please don't forget to include also:
* Library Version.
* Android Version.
* Emulator/Device specs.
* Logs/Crash reports/Stacktraces.
* Example Code/Link to repositories.

**Comment by MichaelStevan** [comment]
I did a function myself, I will be submitting this pull request shortly !

**Comment by cortinico** [comment]
Sweet :) Looking forward

**Comment by cortinico** [comment]
Fixed in the latest version (`v0.3.0`)
