### ISSUE TITLE
app:icon_margin does not work

### ISSUE THREAD

**Issue by GeorgeMina** [cortinico/slidetoact#104]
Setting icon_margin for my slider gives the following error and does not build project:

AAPT: error: attribute icon_margin (aka packageName:icon_margin) not found.

**Comment by cortinico** [comment]
> Setting icon_margin for my slider gives the following error and does not build project:

`icon_margin` is on master but hasn't been released yet. It will be included in the upcoming release

**Comment by cortinico** [comment]
Hey @GeorgeMina, quick heads up that version `0.8.0` has been released with this new feature bundled.
