### ISSUE TITLE
How to change icon programmatically?

### ISSUE THREAD

**Issue by adeldolgov** [cortinico/slidetoact#108]
Hello. Thanks for the library. How can i change icon inside slide button programmatically?

**Comment by cortinico** [comment]
Hi @adeldolgov 
You can easily use the `custom_icon` property to change the slider icon:

https://github.com/cortinico/slidetoact/blob/983de7be73bfd13773092c1981d9e54fd18e4f0f/example/src/main/res/layout/content_custom_icon.xml#L14-L18
