### ISSUE TITLE
Small screen issue

### ISSUE THREAD

**Issue by slimoak** [cortinico/slidetoact#111]
- :white_check_mark: UI Bug / Feature request
![Screenshot 2020-03-30 at 14 42 14](https://user-images.githubusercontent.com/18551562/77913642-e8855580-7294-11ea-932e-a61187c32edc.png)

No control over text positioning. For longer texts and small screens, it is not possible to set the view to show all the text that is covered by the icon. It would be nice to set the text gravity / margin.

Code:
```
<com.ncorti.slidetoact.SlideToActView
        android:id="@+id/slideToStartTripSlider"
        style="@style/SlideToStartTrip"
        android:layout_marginStart="@dimen/material_baseline_grid_2.5x"
        android:layout_marginTop="@dimen/material_baseline_grid_2x"
        android:layout_marginEnd="@dimen/material_baseline_grid_2.5x"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="@+id/swipeToStartGuideline" />
```

```
<style name="SlideToStartTrip">
        <item name="android:layout_height">wrap_content</item>
        <item name="android:layout_width">match_parent</item>
        <item name="area_margin">7dp</item>
        <item name="outer_color">@color/blue</item>
        <item name="inner_color">@color/white</item>
        <item name="border_radius">28dp</item>
        <item name="text_size">@dimen/text.medium</item>
        <item name="slider_height">60dp</item>
        <item name="slider_locked">false</item>
        <item name="slider_icon_color">@color/blue</item>
        <item name="text_appearance">@style/SliderTextAppearance</item>
    </style>
```

```
    <style name="SliderTextAppearance">
        <item name="android:textSize">18sp</item>
        <item name="android:textAllCaps">false</item>
    </style>
```

* Version 0.7.0
* Android Version: 9
* Phones: Motorola G7 / Huawei P9

**Comment by cortinico** [comment]
Hi @slimoak Thanks for reporting.

>  It would be nice to set the text gravity / margin.

Can you please elaborate a bit more here? How text gravity/margin will help you solve your issue? From my point of view you just have to decrease the `textSize`.

**Comment by slimoak** [comment]
Margin could help, for example, in cases like this:
![Screenshot 2020-03-30 at 15 22 05](https://user-images.githubusercontent.com/18551562/77917532-f76f0680-729a-11ea-841b-d0df1da4814f.png)
Reducing the size of the text, unfortunately, is not always the best solution, in this case where all buttons must be visible and legible (application directed to drivers) from a large distance can cause problems at higher resolutions. For the purposes of my project, at this moment, I will probably create a different layout for very small screens, but such feature as preventing the text from being obscured by icon could be useful.

**Comment by cortinico** [comment]
> Margin could help, for example, in cases like this:

I'm sorry but I still don't understand what `margin` should do here.
The text is centered in the view intentionally. Would you like to move the text to the right? How do you know that the size you provide for the margin will suffice?
