### ISSUE TITLE
How to change the text dynamically from code end?

### ISSUE THREAD

**Issue by Sorwar-Hosen-Mostafa** [cortinico/slidetoact#114]
## What kind of issue is this?

 - [ ] UI Bug. Please provide a Screenshot/Video/GIF of what's the problem. If you need help to record a video you can follow [this guide](https://developer.android.com/studio/command-line/adb.html#screenrecord)

 - [ ] Functional Bug. Please describe the scenario of the bug. Furthermore, please spend the time to write a failing test.

 - [x] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

In case of bug report, please don't forget to include also:
* Library Version.
* Android Version.
* Emulator/Device specs.
* Logs/Crash reports/Stacktraces.
* Example Code/Link to repositories.

**Comment by quanta-kt** [comment]
There is a `text` property for this.

Java:
```
slider.setText("Your message");
```
Kotlin
```
slider.text = "Your message"
```

**Comment by cortinico** [comment]
Thanks @quanta-kt for providing the response 👍
