### ISSUE TITLE
iOS like "slide to unlock" animation

### ISSUE THREAD

**Issue by adeldolgov** [cortinico/slidetoact#115]
## What kind of issue is this?
 - [X] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

How to make iOS like "slide to unlock" animation for text? Any ideas?

**Comment by cortinico** [comment]
> How to make iOS like "slide to unlock" animation for text? Any ideas?

Can you be more specific? What is a _iOS like_ "slide to unlock"? 
Do you have a video/gif to share?

**Comment by adeldolgov** [comment]
![shimmer](https://user-images.githubusercontent.com/17458811/80763649-a9724a80-8b47-11ea-9ee0-b9255c259abf.gif)
@cortinico something like this :

**Comment by cortinico** [comment]
That's nothing easy to achieve without an external library like this one:
https://github.com/facebook/shimmer-android

I don't plan to depend on an `shimmer-android` as this will impact all the users. I'm sorry buy I think the easiest approach for you is to fork the library and you use a component from `shimmer-android` to render the text.

**Comment by adeldolgov** [comment]
Thanks :)

пт, 1 мая 2020 г., 1:24 Nicola Corti <notifications@github.com>:
