### ISSUE TITLE
How do I programmatically change the icon for the slider?

### ISSUE THREAD

**Issue by tinolaomahei** [cortinico/slidetoact#118]
This might be related to: https://github.com/cortinico/slidetoact/issues/108, however I don't think the answer under the issue answers the question.

Will there be an option to change the icon programmatically with something like:

```java
slider.setIcon(getDrawable(R.drawable.my_icon));
```

Thanks in advance! Really nice widget :D

**Comment by cortinico** [comment]
Hi @tinolaomahei 
You're right, exposing the icon as a public property is definitely doable.
Happy to review a PR to add this feature :)

**Comment by tinolaomahei** [comment]
My PR for this has been merged to master: https://github.com/cortinico/slidetoact/pull/119

```java
slider.setSliderIcon(R.drawable.my_icon);
```
