### ISSUE TITLE
attribute 'app:slider_icon' not found.

### ISSUE THREAD

**Issue by apurvpatel04** [cortinico/slidetoact#13]
Hi Nicola Corti,

Thank you for this library.

 - Functional Bug. - while adding attribute app:slider_icon gradle build failed with Error:error: attribute 'app:slider_icon' not found.

 

## Details
* Library Version- 0.2.0
* Gradle Version -3.0.1
* Android Studio Version -3.0.1

Thanks

**Comment by cortinico** [comment]
Thanks for reporting @apurvpatel04 

The `app:slider_icon` attribute is fairly new, will be available in the next release (0.3.0) that should be ready around next week.

If you really need to use that attribute now, you need to download this repo and build it locally, the code is on master.

**Comment by cortinico** [comment]
Fixed in the latest version (`v0.3.0`)
