### ISSUE TITLE
Custom fonts via text_appearance attribute does not work on run-time

### ISSUE THREAD

**Issue by diaconori** [cortinico/slidetoact#136]
Hi.

I am trying to customize the font type used in the SlideToActView through the text_appearance attribute, however the widget does not seem to be function properly. 

The widget updates the font types to the new one on design-time but on run-time it reverts back to the original sans-serif font type. 

I am using [Belgano](https://fonts.google.com/specimen/Belgrano) as the theme of my app.

**The view on design-time**
![image](https://user-images.githubusercontent.com/37276987/91890537-ee41f580-ec8f-11ea-852c-978be9717e80.png) 

**The view in xml code**
![image](https://user-images.githubusercontent.com/37276987/91890580-fdc13e80-ec8f-11ea-91d4-ec6eccbc0c86.png) 

**The view on run-time**
![image](https://user-images.githubusercontent.com/37276987/91890616-0ade2d80-ec90-11ea-961c-7a867c4e0d1f.png) 

**The style in xml code**
![image](https://user-images.githubusercontent.com/37276987/91890660-1d586700-ec90-11ea-8d35-09827376f900.png) 

Thanks.

**Comment by cortinico** [comment]
Hi @diaconori 
Thanks for your report. I wasn't unfortunately able to reproduce.

The setup seems really similar to one we have in the sample app:

https://github.com/cortinico/slidetoact/blob/819ae3a122ce11a282c1d0496fa39f72a2af6ada/example/src/main/res/layout/content_text_size.xml#L59-L62

https://github.com/cortinico/slidetoact/blob/819ae3a122ce11a282c1d0496fa39f72a2af6ada/example/src/main/res/values/styles.xml#L23-L28

> I am using Belgano as the theme of my app.

I'm afraid this could be cause. Would you be able to provide an example where I can reproduce the bug? Thank you

**Comment by cortinico** [comment]
Could you also provide the version of the library you're using?

**Comment by diaconori** [comment]
Sorry for the very, very late response. I've had some personal issues to deal with at first but to close this ticket, I've found a 'dirty-fix' with the following code:

GoToPaymentFragment.java - initUserInterface() at onViewCreated:
`mPaymentButton = getActivity().findViewById(R.id.payment_button);
 Typeface font = Typeface.createFromAsset(getActivity().getAssets(), "fonts/belgrano.ttf");
 mPaymentButton.setTypeFace(font.getStyle());`

SlideToView.kt - modified one parameter on the typeface property:
`    /** Typeface for the text field */
    var typeFace = Typeface.NORMAL
        set(value) {
            field = value
            mTextView.typeface = ResourcesCompat.getFont(context, **R.font.belgrano**);
            mTextPaint.set(mTextView.paint)
            invalidate()
        }`

It wont solve the problem unless the specific font type is specified in both the library and the main project, however the code above fixes the problem for now. Forgive me for the late answer and thank you so much for providing this awesome widget.
