### ISSUE TITLE
completeSlider issue

### ISSUE THREAD

**Issue by bryan-ibrahim** [cortinico/slidetoact#145]
completeSlider functionality is **supposed to complete the slider** programmatically if I'm correct - but it only draws a white line from the start to finish of the slider

**Comment by cortinico** [comment]
I've just tested and it works fine on my end.
Can you please provide a reproducer and/or a GIF/Video of what you're experiencing?

**Comment by iridemoshood** [comment]
Its also happening on my end. I have attached a video for your reference.

https://user-images.githubusercontent.com/98904764/202041661-9674d819-0b3e-4c86-ab1a-a3f7569a1312.mov

**Comment by cortinico** [comment]
> Its also happening on my end. I have attached a video for your reference.

Thanks for sharing this @iridemoshood 
What would be the expected behavior as it looks fine to me 🤔

**Comment by iridemoshood** [comment]
@cortinico Was able to resolve it from my end. 
Thanks
