### ISSUE TITLE
ic_check not showing on Samsung 7.1.1 (API 25)

### ISSUE THREAD

**Issue by squeeish** [cortinico/slidetoact#15]
## What kind of issue is this?

UI bug on Android 7.1.1 Samsung Tablet (of course it's a Samsung)

![ezgif com-optimize](https://user-images.githubusercontent.com/3531468/39111840-1ba2e554-4709-11e8-97b7-2419e49e1b7d.gif)

## Details

I cannot replicate this issue on emulators or actual devices. It seems to be an issue with `trimPathStart`/`trimPathEnd`. Notice how the check mark appears briefly after resetting the view.

**Comment by sumaro** [comment]
ic_check.xml in drawable-v25  
`add android:trimPathStart="0.01" `

ic_check is visiable but  without animation

**Comment by cortinico** [comment]
@sumaro Can you provide more context? Are you having the same problem?

**Comment by sumaro** [comment]
@cortinico I copy library "slidetoact" to my project , and fix "ic_check.xml" 

`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportHeight="48.0"
    android:viewportWidth="48.0">
    <path
        android:name="check"
        android:fillColor="#00000000"
        android:pathData="m7.21,25.35l10.3,10.37l23.29,-23.43"
        android:strokeColor="#3D98DE"
        android:strokeWidth="3.5"
        />
</vector>`.

or you can delete "ic_check.xml" in  drawable-v25

**Comment by cortinico** [comment]
Is this still valid @squeeish?
Or can I close it?

**Comment by squeeish** [comment]
Hi @cortinico I'm closing this as I cannot remember anymore. Thanks!
