### ISSUE TITLE
with "Slider reversed" slider icon is reverted too

### ISSUE THREAD

**Issue by onivas** [cortinico/slidetoact#150]
## What kind of issue is this?
 - [ X ] UI Bug: 

<img width="1287" alt="Screenshot 2021-01-29 at 12 30 33" src="https://user-images.githubusercontent.com/5575945/106270726-b20ac500-622e-11eb-9ebe-812cf02f46ae.png">

## Details
When I set `slider_reversed=true`, I need to set a reverted (180 degree) icon in `slider_icon` in order to see it right

* Library Version = 0.9.0

**Comment by cortinico** [comment]
That's a bug. Fix is in #151

**Comment by onivas** [comment]
Prego :)
