### ISSUE TITLE
JCenter distribution

### ISSUE THREAD

**Issue by hannesvoss** [cortinico/slidetoact#152]
[Starting from May 1, 2021 JCenter will stop working.](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) Are there any plans on migrating to another distribution service?
I would love to be able to continue using the project.

**Comment by cortinico** [comment]
Thanks for asking.

The library is already mirrored on Maven Central: https://search.maven.org/artifact/com.ncorti/slidetoact/0.9.0/aar

Newer version of the library will be published to Maven Central only

**Comment by hannesvoss** [comment]
Oh thanks for your reply - I should have checked before. :sweat_smile:

**Comment by cortinico** [comment]
> Oh thanks for your reply - I should have checked before. 😅
> I would suggest changing the readme as it still references the JCenter distribution.

Makes sense 👍  Would like to help me and a send a PR with that 🙏
