### ISSUE TITLE
How to pause or stop animation at this state

### ISSUE THREAD

**Issue by AhmedEssam-SameSystem** [cortinico/slidetoact#154]
![Screen Shot 2021-03-16 at 3 05 18 PM](https://user-images.githubusercontent.com/58694622/111313449-0942e880-8669-11eb-9f1e-9621d3977b1a.png)
## What kind of issue is this?

 - [ ] UI Bug. Please provide a Screenshot/Video/GIF of what's the problem. If you need help to record a video you can follow [this guide](https://developer.android.com/studio/command-line/adb.html#screenrecord)

 - [ ] Functional Bug. Please describe the scenario of the bug. Furthermore, please spend the time to write a failing test.

 - [x] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

In case of bug report, please don't forget to include also:
* Library Version.
* Android Version.
* Emulator/Device specs.
* Logs/Crash reports/Stacktraces.
* Example Code/Link to repositories.[
![Screen Shot 2021-03-16 at 3 20 14 PM](https://user-images.githubusercontent.com/58694622/111315521-21b40280-866b-11eb-99df-58a1e5785407.png)
](url)

**Comment by cortinico** [comment]
>     * [x]  Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

Can you be more clear?
