### ISSUE TITLE
Unable to change colors at runtime.

### ISSUE THREAD

**Issue by Andresteve07** [cortinico/slidetoact#16]
## What kind of issue is this?

 - [ ] UI Bug. Please provide a Screenshot/Video/GIF of what's the problem. If you need help to record a video you can follow [this guide](https://developer.android.com/studio/command-line/adb.html#screenrecord)

 - [x] Functional Bug. Please describe the scenario of the bug. Furthermore, please spend the time to write a failing test.

 - [ ] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

* Library Version. **0.3.0**
* Android Version. 
* Emulator/Device specs. **LG Q6 Android 7.1.1 **
* Logs/Crash reports/Stacktraces.
* Example Code/Link to repositories.

I'm working on a java based android app.
Trying to integrate this view to the project I found a problem.
I don't seem to be able to change dynamically the outer colour nor the inner either.
The slider will be displayed with not even the xml defined colours but some weird defaults as shown in the screen shot.

![alt text](https://image.ibb.co/cX1i3y/slider_shot.png "ScreenShot")

Am I doing something wrong?
```java
final SlideToActView actionSlider = (SlideToActView) rowView.findViewById(R.id.slider);
actionSlider.setOuterColor(R.color.slider_outer_color);
actionSlider.setInnerColor(R.color.slider_inner_color);
actionSlider.setLocked(false);
```

**Comment by cortinico** [comment]
Hey @Andresteve07 

Thanks for reporting this (and using the library).
This is caused by those two lines:

```
actionSlider.setOuterColor(R.color.slider_outer_color);
actionSlider.setInnerColor(R.color.slider_inner_color);
```

You can't pass Color resources to those methods, but you must pass a Color Int.
Replace with those two lines and it should work as expected.

```
actionSlider.setOuterColor(ContextCompat.getColor(context, R.color.slider_outer_color));
actionSlider.setInnerColor(ContextCompat.getColor(context, R.color.slider_inner_color));
```
