### ISSUE TITLE
how to make button to default state (unSlided after onslide complete) 

### ISSUE THREAD

**Issue by Dhananjaypathak27** [cortinico/slidetoact#162]
## What kind of issue is this?

I want to know how to make a button to default side state (unslided) on slide complete as in my code I have to call API for slide complete and move to a new page but the user can come back to the previous page where he is unable to slide the button as it is already slid.

**Comment by cortinico** [comment]
> I want to know how to make a button to default side state (unslided) on slide complete as in my code I have to call API for slide complete and move to a new page but the user can come back to the previous page where he is unable to slide the button as it is already slid.

Have you tried to use the `resetSlider()` function?

**Comment by gururani-abhishek** [comment]
> ## What kind of issue is this?
> I want to know how to make a button to default side state (unslided) on slide complete as in my code I have to call API for slide complete and move to a new page but the user can come back to the previous page where he is unable to slide the button as it is already slid.
try this : 
sliderButtonReference.isLocked = true

**Comment by cortinico** [comment]
Closing due to lack of response
