### ISSUE TITLE
completeSlider

### ISSUE THREAD

**Issue by smiesnyrobert** [cortinico/slidetoact#164]
When completeSlider() function is called from eg. **onCreateView in fragmen** animation works bad. 

Just draws endIcon stretched. Then when manually swipe button its working, or when calling completeSlider() from onClick other button its working too. 

    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_login, container, false);

        swipeButton = view.findViewById(R.id.swipeBtn);
        swipeButton.completeSlider();
        return view;
    }

![bug](https://user-images.githubusercontent.com/33247860/130359295-98db3cc7-487b-4df7-8597-7ef60ea65d4a.png)

Can u please fix this? Thank you.

**Comment by cortinico** [comment]
> When completeSlider() function is called from eg. onCreateView in fragmen animation works bad.

Is it something that is happening ONLY when you call `completeSlider()` in the `onCreateView`? 
Also why do you need to do so? Have you tried doing it from `onViewCreated` instead?

**Comment by smiesnyrobert** [comment]
Yes i tried onCreateView, onViewCreated, onCreate, onBindViewHolder.
I just need recyclerview with list of items. Every item has SlideToActView and some of them must be in complete state and some of them in "initial/reset" state.

Maybe some function like setState(COMPLETE/INITIAL) will be perfect.

**Comment by cortinico** [comment]
Yup I see your point. Would you be able to setup a reproducer (like a sample app with the RecyclerView and the sliders)? That will help my investigate and fix this issue faster 🙏

**Comment by nataliialapshyna-dna** [comment]
@cortinico  Please take a look at PR with the possible solution for this issue.
