### ISSUE TITLE
SlideOnCompleteListener not called when slider is locked.

### ISSUE THREAD

**Issue by Sanjay026** [cortinico/slidetoact#167]
Method slider.setOnSliderCompleteListener() not called when the slider is locked. 
Which method should be called when slider reached to the right most side ?

**Comment by cortinico** [comment]
Duplicates #161

**Comment by Sanjay026** [comment]
@cortinico That is Duplicate but you have not shared the proper answer of that Please give the proper answer because slideOnCompleteListener wont call when the slider is locked.
