### ISSUE TITLE
How can I disable SlideToActView until I want.

### ISSUE THREAD

**Issue by mujahid-iitr** [cortinico/slidetoact#173]
I want to disable slide to unlock feature until my UI filed has proper validation.
For example, I have a mobile field and SlideToActView on my screen , until user enter mobile number,  I want to disable SlideToActView.
After user entered the mobile number, I want to make it enable.

**Comment by cortinico** [comment]
You can used the `slider_locked` attribute:
https://github.com/cortinico/slidetoact#slider_locked

```
SlideToActView sta = (SlideToActView) findViewById(R.id.slider);
sta.setLocked(true);
```
