### ISSUE TITLE
Can I implement such slide using this library?

### ISSUE THREAD

**Issue by anonym24** [cortinico/slidetoact#199]
![image](https://user-images.githubusercontent.com/8851301/184550371-c3e351d2-0587-4915-961f-20e312498311.png)

so basically it's white handle with shadow (on the right) on white background

**Comment by HelgeApps** [comment]
so basically it's white handle with shadow (on the right) on white background

**Comment by cortinico** [comment]
Mostly yes,

> with shadow

The shadow on the right will be the hardest thing to achieve though. This library adds some shadow but not as prominent as in this screenshot

**Comment by anonym24** [comment]
@cortinico thanks for reply.
Yeah. I tried 

![image](https://user-images.githubusercontent.com/8851301/184634627-5b0a3416-bd39-48a7-bb87-719f9626c751.png)

Shadow is not that important. I changed inner background.

Two more things:

- text is always in the middle of the outer, would be great it to be with offset from button
- button (outer) aspect size is 1:1 only, would be great to have an ability to set size or aspect ratio

**Comment by cortinico** [comment]
> * text is always in the middle within the inner, would be great to have it with offset from button (outer)
>     * button (outer) aspect size is 1:1 only, would be great to have an ability to set size or aspect ratio

Yup those two are not possible at the moment
