### ISSUE TITLE
No animation when slider complete

### ISSUE THREAD

**Issue by daniel-gk8** [cortinico/slidetoact#202]
## What kind of issue is this?

Is there a way to not have the animation (shrink to circle) when the slider is complete and keep it the same size?
Thanks

**Comment by cortinico** [comment]
> Is there a way to not have the animation (shrink to circle) when the slider is complete and keep it the same size?

Sorry I don't understand your question. Coudl you clarify (whith an image, maybe)?

**Comment by daniel-gk8** [comment]
![image](https://user-images.githubusercontent.com/106020409/187949867-3f81ffdc-c24f-459a-9add-e43f769a6fa2.png)

The slider turns into a circle at the end with a checkmark. I would like it to stay as a slider and not do that

**Comment by daniel-gk8** [comment]
I found how to do it:
` app:animate_completion="false"`
