### ISSUE TITLE
onSlideComplete issue

### ISSUE THREAD

**Issue by iraunit** [cortinico/slidetoact#204]
when calling onSlideComplete it should do some task but it is not.

code:-
stopAlarmButton.onSlideCompleteListener?.onSlideComplete(SlideToActView(this,))
![image](https://user-images.githubusercontent.com/82479754/189515987-2ba658dd-09a0-49ed-bde6-b3f86138018c.png)
![image](https://user-images.githubusercontent.com/82479754/189516009-0a51cd72-f086-416d-84d6-8f7aa2fb6e07.png)

How to use this  to do something when sliding is completed?

**Comment by cortinico** [comment]
> stopAlarmButton.onSlideCompleteListener?.onSlideComplete(SlideToActView(this,))

You're calling this wrong. You can find an example on how to call this here:
https://github.com/cortinico/slidetoact/blob/aaccbde3e4aacc00827689aefdda0daf50a6d1a7/example/src/main/java/com/ncorti/slidetoact/example/SampleActivity.java#L146-L151
