### ISSUE TITLE
Is there any way to programatically slide this slidetoact slider button?

### ISSUE THREAD

**Issue by rsuman132** [cortinico/slidetoact#216]
Is there any way to programatically slide this slidetoact slider button without user interaction

**Comment by cortinico** [comment]
I've already answered you here: https://github.com/cortinico/slidetoact/issues/214
It's written in the README:

With full slide animation:

```java
SlideToActView sta = (SlideToActView) findViewById(R.id.slider);
sta.setCompleted(completed: true, withAnimation: true);
```

Without slide animation:

```java
SlideToActView sta = (SlideToActView) findViewById(R.id.slider);
sta.setCompleted(completed: true, withAnimation: false);
```
