### ISSUE TITLE
Allow slider icon to be animated

### ISSUE THREAD

**Issue by LethalMaus** [cortinico/slidetoact#231]
## What kind of issue is this?

 - [ ] UI Bug. Please provide a Screenshot/Video/GIF of what's the problem. If you need help to record a video you can follow [this guide](https://developer.android.com/studio/command-line/adb.html#screenrecord)

 - [ ] Functional Bug. Please describe the scenario of the bug. Furthermore, please spend the time to write a failing test.

 - [x] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

Is it possible to have the slider icon animated if it the user provides a animated vector?

**Comment by cortinico** [comment]
> Is it possible to have the slider icon animated if it the user provides a animated vector?

That's already possible:
https://github.com/cortinico/slidetoact#complete_icon

**Comment by LethalMaus** [comment]
The completed icon is animated not the slider icon

**Comment by LethalMaus** [comment]
I mean the the slider icon, not the completed icon

**Comment by cortinico** [comment]
The slider icon can't be animated as I don't see how would fit. The icon is already rotated as the user slides. Should the icon animate in a loop and also be rotated as the user swipes?
