### ISSUE TITLE
Bounce effect feature request

### ISSUE THREAD

**Issue by artemcarabash** [cortinico/slidetoact#232]
Hello everyone, 
we are faced with the need to create a jumping animation for the slider, thereby showing the user that this is a slider that needs to be swiped to the right (yes, this is weird, but some users do not really understand this). I wanted to know if such an option is already available and I was looking badly or if it really is not supported by the library.
For reference, I attached a gif of the effect I'm trying to achieve from below.

![bounce](https://user-images.githubusercontent.com/16085964/212177409-8565c2ab-86ec-4af1-a7fd-4e7ed4db0333.gif)

Thanks in advance!

**Comment by cortinico** [comment]
>  I wanted to know if such an option is already available and I was looking badly or if it really is not supported by the library.
For reference, I attached a gif of the effect I'm trying to achieve from below.

That's not supported out of the box, but I'm more than happy to review a PR about it :)

**Comment by artemcarabash** [comment]
Challenge accepted 😆
