### ISSUE TITLE
Disabled state

### ISSUE THREAD

**Issue by zeroDivider** [cortinico/slidetoact#255]
## What kind of issue is this?
 - [x] Feature Request

## Details

I am working on the app where I am using `SwipeToActView` and at some point I must forbid user to do the action swiping if they did not confirm something. In that case, it would be great to have disabled state of swipe button.

I have tried using selector for states enable and disabled, but it seems `app:outer_color` cannot take `@drawable`.
My solution was coloring it and locking+disabling manually. Additionally, I spotted some light gray line under swipe text (my guess is baseline) - looking ugly.

Thanks :)

**Comment by cortinico** [comment]
You can lock the slider (https://github.com/cortinico/slidetoact#slider_locked) as you also suggested to achieve this. I'm not sure what you're asking for also.
Plus can you share a screenshot of your UI bug?

**Comment by zeroDivider** [comment]
I would like to have something like this:
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_enabled="false" android:color="@color/disabled_gray" />
    <item android:state_enabled="true" android:color="@color/enabled_red" />
</selector>
```
then:
```
<com.ncorti.slidetoact.SlideToActView
     ....
     app:outer_color="@drawable/my_selector_bg_swipe"
     app:innte_color="@drawable/my_selector_bg_swipe_button"
    ....
    />
```
Then I'd like to disable the view like this:
```
binding.swipeButton.isEnabled = false
```
and then the component does some magic (what my request is about :D) and color itself, so I don't have to do it manually.

I thought it may already have something like this as numerous other components... I hope it is not something subnormal I am asking for.

As for UI bug, I'll open new ticket.

**Comment by cortinico** [comment]
Thanks for the clarification. That's a bug on the widget.
It's fixed here:
- https://github.com/cortinico/slidetoact/pull/264
