### ISSUE TITLE
Coloring swipe button makes grey line under text

### ISSUE THREAD

**Issue by zeroDivider** [cortinico/slidetoact#257]
## What kind of issue is this?

 - [X] UI Bug

## Details

* Library Version: `0.9.0`, `0.10.0`
* Android Version: 12
* Device specifics: Poco F4
* Example Code:
```
val sliderColor: Int
val arrowColor: Int
if (isDisabled) {
   sliderColor = R.color.inner_border
   arrowColor = R.color.text_slider_desc
} else {
   sliderColor = R.color.red_splash
   arrowColor = R.color.yellow
}

binding.btnOrder.isLocked = isDisabled
binding.btnOrder.isEnabled = !isDisabled

binding.btnOrder.outerColor = resources.getColor(sliderColor, null)
binding.btnOrder.innerColor = resources.getColor(arrowColor, null)
```

![grey_line_screenshot](https://user-images.githubusercontent.com/17478088/230043601-c88ee855-79a3-48c8-b45a-4334b63d59c3.jpg)

_Note:_ the issue is not happening on `Google Pixel 7 Pro` with android 13

**Comment by cortinico** [comment]
Just tested on an emulator and cannot reproduce:

![Screenshot_1682189655](https://user-images.githubusercontent.com/3001957/233801720-420b85b2-8be8-4eac-b4d1-14230a615778.png)

I believe this is sadly device specific to Poco F4, there is not much I can do here

**Comment by zeroDivider** [comment]
Hi, I completely understand that you may not want to lose time support some totally not important models, but guy form my office with SAMSUNG S22 (I will provide more details when I get them) has the same issue.

Not sure it is one of these devices.

Also, Poco is premium derivate of Xiaomi.
I know it works on emulator, just like physical Pixel 7 Pro - checked personally, but it is not the only device on the market. My client will test it on Samsung most definitely and we'll have to act on the problem.

So, I am asking you - please, reopen the issue and research deeper.

**Comment by cortinico** [comment]
Here a screenshot on a Samsung S22:
![screen-1682245452](https://user-images.githubusercontent.com/3001957/233834293-d132992b-6d13-4939-98d8-52f6012ef5b5.png)

I still see no problem in it.
