### ISSUE TITLE
Bounce is not released yet?

### ISSUE THREAD

**Issue by ishaangarg** [cortinico/slidetoact#275]
## What kind of issue is this?

Feature Request

## Details

Bounce feature is added to readme but is lacking from v0.10 as far as I could check.

Also, would be great to have the bounce animation start on demand, so we can bounce the slider icon when btn is clicked instead of swiped

**Comment by cortinico** [comment]
Correct, that's on `main` but hasn't been released yet. It will be included in the next release `0.11`

**Comment by cortinico** [comment]
I've just released https://github.com/cortinico/slidetoact/releases/tag/v0.11.0 which contains the bounce feature
