### ISSUE TITLE
border_radius not working in 'com.ncorti:slidetoact:0.10.0'

### ISSUE THREAD

**Issue by heihitesh** [cortinico/slidetoact#276]
## What kind of issue is this?

 - [x] UI Bug. Please provide a Screenshot/eeVideo/GIF of what's the problem. If you need help to record a video you can follow [this guide](https://developer.android.com/studio/command-line/adb.html#screenrecord)

 - [ ] Functional Bug. Please describe the scenario of the bug. Furthermore, please spend the time to write a failing test.

 - [ ] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details
![reminder](https://github.com/cortinico/slidetoact/assets/13065741/4df7e782-0bac-447b-a09d-2e6d86ddf342)

Note 
border_radius is working in 'com.ncorti:slidetoact:0.9.0'

In case of bug report, please don't forget to include also:
* Library Version.
* Android Version : 34
* Emulator/Device specs : Real Device 
* Logs/Crash reports/Stacktraces.
* Example Code/Link to repositories.

**Comment by cortinico** [comment]
Can you try again on 0.10.0? Any specific reason why you're on 0.9 @heihitesh ?

**Comment by heihitesh** [comment]
I have tried in 0.10.0 already, it does not works 
Thats why I am using 0.9.0 
Thank You

**Comment by cortinico** [comment]
> Thats why I am using 0.9.0

Sorry I don't understand why you're using 0.9 if what you're reporting is broken on both version

**Comment by heihitesh** [comment]
Hi, 
I never told that its not working in 0.9. 

Let me be clear again 

IT IS WORKING IN 0.9 
IT IS NOT WORKING IN 0.10

Thank You

**Comment by cortinico** [comment]
I was able to find this bug and fix it:
- https://github.com/cortinico/slidetoact/pull/285

This will be shipped in 0.11.0

**Comment by cortinico** [comment]
https://github.com/cortinico/slidetoact/releases/tag/v0.11.0 is now out with this fic
