### ISSUE TITLE
Unable to automate the custom view that is implemented from slide to act using Appium

### ISSUE THREAD

**Issue by GregoryPyreddy** [cortinico/slidetoact#279]
## What kind of issue is this?

 - [ ] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

In case of bug report, please don't forget to include also:
* Library Version.
* Android Version.
* Emulator/Device specs.
* Logs/Crash reports/Stacktraces.
* Example Code/Link to repositories.

Please let me know if you have any issues

**Comment by cortinico** [comment]
Closing as the issue body is fully missing
