### ISSUE TITLE
Suggestion | Same color for text and inner circle

### ISSUE THREAD

**Issue by dhruv0singh** [cortinico/slidetoact#28]
## What kind of issue is this? - Suggestion not an issue

Please provide the function to change the text color and inner circle color based on the value provided by the user. Having the same color for the inner circle and text color doesn't fulfill all requirements.

**Comment by cortinico** [comment]
Yeah that sounds great. I'll anyway default the text color to the `secondaryColor`

**Comment by cortinico** [comment]
Done, will be available in the upcoming release of the library

**Comment by cortinico** [comment]
It's available on `0.5.0`, just released!
