### ISSUE TITLE
Not working with TalkBack/Screenreader

### ISSUE THREAD

**Issue by pachi81** [cortinico/slidetoact#380]
## What kind of issue is this?

 - [ ] UI Bug. Please provide a Screenshot/Video/GIF of what's the problem. If you need help to record a video you can follow [this guide](https://developer.android.com/studio/command-line/adb.html#screenrecord)

 - [x] Functional Bug. Please describe the scenario of the bug. Furthermore, please spend the time to write a failing test.

 - [x] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

This element is not detect by screenreader for TalkBack. So blind people can not access this item.
Or is there any special setting for? 
Thank you!

**Comment by cortinico** [comment]
Thanks for the report, fix is here:
- https://github.com/cortinico/slidetoact/pull/384
