### ISSUE TITLE
How to make it vertical?

### ISSUE THREAD

**Issue by ls29322** [cortinico/slidetoact#41]
First of all: amazing job right here!

I was wondering if there is a way to make the slider vertical (from down to up for example?)

Thanks for the information! :D

**Comment by cortinico** [comment]
Hey @ls29322 

> First of all: amazing job right here!

Thanks :)
So would something like this be ok for you?

![screenshot_1543096434](https://user-images.githubusercontent.com/3001957/48973285-51731280-f03c-11e8-8d4c-515be126fbe8.png)

I have a branch where I'm doing it. I'm still not sure I'm going to merge this as all the library was designed to have an horizontal slider.

Anyway the commit is here 35e76f11421be69c4558117a42d9b6b2cc3c3973
Looking forward your feedback

**Comment by ls29322** [comment]
Oh! That's nice, I achieve it with just adding the "rotation" property, but of course the layout go a little bit crazy ^^

**Comment by cortinico** [comment]
Hey @ls29322 
So looks like it works fine with `ConstraintLayout` as well.

I pushed an example commit for you here: f8d8a6d525739cb62bb9cc360e14147c02a7ba7e
The result is like this:

![screenshot_1543359078](https://user-images.githubusercontent.com/3001957/49116927-5aafe980-f29f-11e8-8820-a90783c53d79.png)
