### ISSUE TITLE
Change the font family on slide text

### ISSUE THREAD

**Issue by IreneTrullen** [cortinico/slidetoact#46]
Can I change the font family on slide text?

**Comment by cmahopper** [comment]
@cortinico Any update on this?

**Comment by cortinico** [comment]
This is related to #51 
I'm going to make sure the text inside the `SlideToActView` is a TextView and easier to customize.

**Comment by slegaitis** [comment]
Any update on this?

**Comment by slegaitis** [comment]
Changing font family can be done as such: 

private var typeFace = Typeface.NORMAL
        set(value) {
            field = value
            mTextPaint.typeface = Typeface.create(ResourcesCompat.getFont(context, R.font.regular_font), value)
            invalidate()
        }
