### ISSUE TITLE
onSlideComplete doesn't call

### ISSUE THREAD

**Issue by BrayanMC** [cortinico/slidetoact#49]
I'm using kotlin and the onSlideComplete is not called. Will you have an example?

Thank you.

**Comment by BrayanMC** [comment]
I could achieve it. Thank you.

**slide.onSlideCompleteListener = object : SlideToActView.OnSlideCompleteListener {
            override fun onSlideComplete(view: SlideToActView) { 
    ..........
     }
}**

**Comment by cortinico** [comment]
Thanks :)
