### ISSUE TITLE
please support android minSdkVersion 14 or less.

### ISSUE THREAD

**Issue by camelsmith** [cortinico/slidetoact#5]
please support android minSdkVersion 14 or less.Beacuse still have lots of user use phone follow in Android 5.0，if minSdkVersion is higher,that mean lots of people can not use this library.
    I suggest auther provide two version for this library(slidetoact),one is use in minSdkVersion 14 or less,and another is use in minSdkVersion 21.
   thanks.

**Comment by cortinico** [comment]
It's on master now :) Will be released in the upcoming release of the library. 
If you need it now, you can checkout master and build an artifact.
