### ISSUE TITLE
How to show the completed state?

### ISSUE THREAD

**Issue by kostasoft** [cortinico/slidetoact#52]
Thanks for the library! But how to make slideToActView run immediately in a completed state?

**Comment by cortinico** [comment]
Hey @kostasoft
Thanks for the feedback, 

> Thanks for the library! But how to make slideToActView run immediately in a completed state?

Do you mean with or without animation?

**Comment by kostasoft** [comment]
No animation. Run immediately in a collapsed form (tick in a circle)

> Do you mean with or without animation?

**Comment by cortinico** [comment]
Hey @kostasoft

So as of today, there is no easy way to achieve what you want.
I'll keep it open so I can provide better support for changing the slider stats programmatically in the near future.

**Comment by benjdero** [comment]
@cortinico How can I achieve the reverse animation ? I would like the slider to start collapsed while some data is loading, and then, once it's finished loading, to expand and start the normal behavior.

**Comment by cortinico** [comment]
As previously commented, currently is not supported. We should implement the support for changing the slider stats programmatically. If someone from the community is willing to take this issue, I'm happy to review a PR :)
