### ISSUE TITLE
API 17: Resources$NotFoundException

### ISSUE THREAD

**Issue by kostasoft** [cortinico/slidetoact#53]
android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/ic_call_white_24dp.png from xml type xml resource ID #0x7f0800ca

Refers to a line of code:
`val parser = res.getXml(resId)`
In the method **parseVectorDrawableCompat**

Physically, the picture res/drawable/ic_call_white_24dp.xml is present. 

Enable
`vectorDrawables.useSupportLibrary = true`
it is not possible, the application crashes, you will have to redo much in the application code

There are no problems on API 21 and above.

**Comment by kostasoft** [comment]
I had to turn on the setting:
vectorDrawables.useSupportLibrary = three
And fix all the errors in my code

**Comment by cortinico** [comment]
Thanks for the feedback @kostasoft
