### ISSUE TITLE
Render Problem in android studio 3.3.1

### ISSUE THREAD

**Issue by mrb0098** [cortinico/slidetoact#55]
i add this lib to my project and get render problem : 

`java.lang.ClassCastException: android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.VectorDrawable   at android.graphics.drawable.AnimatedVectorDrawable.inflate(AnimatedVectorDrawable.java:546)   at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)   at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)   at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)   at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1266)   at com.android.layoutlib.bridge.impl.ResourceHelper.getDrawable(ResourceHelper.java:338)   at android.content.res.Resources_Delegate.getDrawable(Resources_Delegate.java:186)   at android.content.res.Resources.getDrawable(Resources.java:827)   at com.ncorti.slidetoact.SlideToActView.<init>(SlideToActView.kt:227)   at com.ncorti.slidetoact.SlideToActView.<init>(SlideToActView.kt:37)   at com.ncorti.slidetoact.SlideToActView.<init>(SlideToActView.kt:-1)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)   at android.view.LayoutInflater.inflate(LayoutInflater.java:394)`

**Comment by cortinico** [comment]
Hey @mrb0098 Can you please provide more context on this?
Have you customized the `SlideToActView` somehow? If yes, how?

Can you attach here the XML file that you're trying to preview?

**Comment by mrb0098** [comment]
hi
its very interesting
i can use this lib in a new project without any problem
but in my project i have this problem
and i didnt any edit on this lib

**Comment by cortinico** [comment]
Would you be able to send me a small project where you're able to reproduce the issue?

**Comment by mrb0098** [comment]
i try to create a project with that issue .

may be the issue because of interference between the libs i implement to my project 🤔🤔

**Comment by cortinico** [comment]
Any updates?

**Comment by cortinico** [comment]
@mrb0098 any updates?

**Comment by UmarFarooqOO7** [comment]
i have same issue.
I'm using Android Studio 3.4.2
Build #AI-183.6156.11.34.5692245, built on June 27, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by cortinico** [comment]
@UmarFarooqOO7 Please open another issue with details on the library version you're using.
If you're also able to provide a sample project where I can reproduce the issue would be extremely valuable.
