### ISSUE TITLE
feature request: Attribute to change arrow icon DP

### ISSUE THREAD

**Issue by druby-luke** [cortinico/slidetoact#61]
## What kind of issue is this?

 - [ ] UI Bug. Please provide a Screenshot/Video/GIF of what's the problem. If you need help to record a video you can follow [this guide](https://developer.android.com/studio/command-line/adb.html#screenrecord)

 - [ ] Functional Bug. Please describe the scenario of the bug. Furthermore, please spend the time to write a failing test.

 - [x] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

I would like a attribute to manually set the DP for the icon arrow.
this would be awesome for lower value slider_height like 40dp.
![c54711d1-4ad0-466d-95b2-33a1f6f75343 png](https://user-images.githubusercontent.com/11366524/53325905-9da44c00-38e4-11e9-976a-e99d1afaddb9.jpg)

**Comment by cortinico** [comment]
> I would like a attribute to manually set the DP for the icon arrow.
this would be awesome for lower value slider_height like 40dp.

@druby-luke do you have a screenshot for what you would love to achieve?
So far as I understand, you would love to have the arrow even if the slider is small right?

**Comment by tsaulic** [comment]
I would also love this feature.

**Comment by cortinico** [comment]
> I would also love this feature.

Hey @tsaulic can you be a bit more specific?
What exactly are you trying to achieve?

**Comment by tsaulic** [comment]
> > I would also love this feature.
> 
> Hey @tsaulic can you be a bit more specific?
> What exactly are you trying to achieve?

Oh, just wanted to be able to specify the size of the icon when I use for example 
`app:area_margin="0" `
and my `app:slider_height=""` is anything under 42dp, the icon often is almost invisible, like in the screenshot provided by @druby-luke in an above post.

I got around it by providing `app:slider_height="42dp"` which is the minimum size for it to look good, but it would be ideal if I could, for example, set it to 24dp and tweak the scaling of icon/container via a different property.

Thanks for responding!

**Comment by cortinico** [comment]
Hey @tsaulic @druby-luke 
So you can tweak the icon margin just by providing an override to the `default_icon_margin` resource in your app (the default is `16dp`).

So just add this in your `dimens.xml`:
```
<resources>
    <dimen name="default_icon_margin">0dp</dimen>
</resources>
```
To have something like:
<img width="397" alt="Screenshot 2019-04-29 at 15 26 51" src="https://user-images.githubusercontent.com/3001957/56899233-3b59fa00-6a93-11e9-8b82-3c6031e1544e.png">


And this:
```
<resources>
    <dimen name="default_icon_margin">100dp</dimen>
</resources>
```
To have something like:
<img width="395" alt="Screenshot 2019-04-29 at 15 25 42" src="https://user-images.githubusercontent.com/3001957/56899189-25e4d000-6a93-11e9-94f9-b5b799557c85.png">

This should be enough to solve your issue.
If you need more fine grain control we should probably add an extra attribute to control it, but I'd love to do it only if there are more requests for this specific feature.
