### ISSUE TITLE
slider_reversed and slider_icon_color attributes not working

### ISSUE THREAD

**Issue by bitamirshafiee** [cortinico/slidetoact#71]
Details

can't use attributes slider_reversed and slider_icon_color
* Library 0.6.0.
*gradle version : 3.4.0
*Android Studio Version -3.4

**Comment by cortinico** [comment]
Hey @bitamirshafiee 
The attributes `slider_reversed` and `slider_icon_color` don't work as they're included only in the version `0.7.0` of the library. Please update to that version.
