### ISSUE TITLE
Make the slide as a selector (prevent it from transforming into check)

### ISSUE THREAD

**Issue by Erinel** [cortinico/slidetoact#72]
- Feature Request. I want to make a slider but that does not complete, that just behaves like a selector, on completion check does not appear, instead slider text changes along with screen behavior, and you can restore previous behaviour sliding the other way.

**Comment by cortinico** [comment]
Hey @Erinel 
Thanks for the suggestion. Just a couple of question.

* What about the icon? Should it be an arrow? 
* Which icon should be displayed when the slider is in the _selected_ state?
* Currently the slider has a 80/20 behavior. The slider will not complete if you don't drag it over the 80% of the progress. How about the restore scenario? Should it behave symmetrically?

I'm not really sure I'm going to implement this but I'm just gathering ideas

**Comment by Erinel** [comment]
I think the icon should be the arrow, in the selected state it should remain at the other side of the slider (with the inverted arrow), and about dragging, it should have same 80/20 behaviour symmetrically.
Thanks for your response!

**Comment by cortinico** [comment]
Hey @Erinel 
I've just submitted a draft PR #74 
Can I ask you to take a look and give me your opinion?

**Comment by cortinico** [comment]
Closing as apparently there was no interest in the feature
