### ISSUE TITLE
Text gravity attribute

### ISSUE THREAD

**Issue by Bendor** [cortinico/slidetoact#78]
First of all, thanks for your awesome button! 
Could you please add text gravity attribute, it will help me a lot! Thanks

**Comment by cortinico** [comment]
Hi @Bendor 
Thanks for reporting.

I don't think I'm going to add this feature to slidetoact as it will complicate even more the code for computing the position of the text. Moreover it feels natural from the UX point of view to have the text centered. I don't think this is a feature that a lot of other users will benefit from.

I can invite you to fork the library and change the code that is computing the text positioning here:

https://github.com/cortinico/slidetoact/blob/b921af58d1565da5d6a6dd2594c35a94570c5720/slidetoact/src/main/java/com/ncorti/slidetoact/SlideToActView.kt#L364-L366

to match your desired positioning. Please let me know if you need further help, I'm happy to support :)
