### ISSUE TITLE
Migrate to androidx

### ISSUE THREAD

**Issue by abhijeet-nkt** [cortinico/slidetoact#80]
Shouldn't it be migrated to androidx ?
I wanted to use this in my project, but noticed that the library isn't migrated to androidx (but my project is). This make it unusable in my project

**Comment by cortinico** [comment]
Yeah @abhijeet-nkt you're right.
I'm happy to receive a PR for this (you're more than welcome to do it :D)

Ideally the upcoming version of slidetoact (0.8.0) will be AndroidX compatible only.

> This make it unusable in my project

In the meanwhile, you can still use Jetifier (https://developer.android.com/studio/command-line/jetifier) and use slidetoact in your project.

**Comment by ThinkHattke** [comment]
@cortinico can I migrate it to androidx?

**Comment by cortinico** [comment]
Sure please go ahead @ThinkHattke :)
