### ISSUE TITLE
Change the circle icon when sliders sliding completed

### ISSUE THREAD

**Issue by rushix123** [cortinico/slidetoact#88]
## When Sliders sliding gets complete, then how can i change the circle image with tick to a custom button?
 

I liked this library very much, nice work and appreciated response from you guys

**Comment by cortinico** [comment]
Hi @rushix123 
Thanks for using the library and asking this question.

Currently there is no public API to expose this property (we might add it in the future if there is enough demand from the community).

The current workaround that you can try, is to provide an `<animated-vector>` resource in your library project called `slidetoact_animated_ic_check.xml`.

Having such a file in the app project, will cause the resource provided by the library to be overridden. I haven't tested this workaround but it should work properly on API 21 and above.
