### ISSUE TITLE
How can i increase animation time and make it quick?

### ISSUE THREAD

**Issue by rushix123** [cortinico/slidetoact#89]
In your documentation it is there -

val sta = (SlideToActView) findViewById(R.id.slider);
sta.animDuration(600)

But my code is in java and i do not know kotlin language, How can i call the same function in java?

**Comment by cortinico** [comment]
Hi @rushix123 
Thanks for asking this question.

Please note that the Animation Duration attribute was recently merged on master and is not available in any release yet. You would have to either build the library manually or wait for a new release.

> But my code is in java and i do not know kotlin language, How can i call the same function in java?

You can easily achieve the same result with:

```java
            SlideToActView sta = findViewById(R.id.slider);
            sta.setAnimDuration(123);
```

in Java
