### ISSUE TITLE
Hi how to add text style bold in slide to act 

### ISSUE THREAD

**Issue by jesuvijay** [cortinico/slidetoact#9]
Add text style bold in slide to act

**Comment by jesuvijay** [comment]
okay i will try

**Comment by cortinico** [comment]
Fixed in the latest version (`v0.3.0`)

**Comment by IreneTrullen** [comment]
Can I change the font family on slide to act text?

**Comment by cortinico** [comment]
@IreneTrullen Can you open another issue. This one is closed.
