### ISSUE TITLE
How to create the button programmatically and modify attributes like text, color, etc?

### ISSUE THREAD

**Issue by habosoft1** [cortinico/slidetoact#91]
## What kind of issue is this?

 - [ ] UI Bug. Please provide a Screenshot/Video/GIF of what's the problem. If you need help to record a video you can follow [this guide](https://developer.android.com/studio/command-line/adb.html#screenrecord)

 - [ ] Functional Bug. Please describe the scenario of the bug. Furthermore, please spend the time to write a failing test.

 - [ ] Feature Request. Start by telling what's problem you’re trying to solve. A Pull request is welcome as well.

## Details

In case of bug report, please don't forget to include also:
* Library Version.
* Android Version.
* Emulator/Device specs.
* Logs/Crash reports/Stacktraces.
* Example Code/Link to repositories.

**Comment by cortinico** [comment]
Hi @habosoft1 
You can achieve the desired behavior by just creating a `SlideToActView` class  (using one of the 3 constructor) and attaching it to a `ViewGroup`.

Here an example in Java:

```java
        SlideToActView newSlider = new SlideToActView(this); // this is a Context
        newSlider.setText("Test");

        LinearLayout container = findViewById(R.id.linear_layout);
        container.addView(newSlider);
```
